- name: Get Token from manager
  shell:
    docker swarm join-token {{ swarm_role }} |
    grep token  |
    sed -e "s/^.*token //"  # -e "s/ .*$//"
  register:     swarm_token
  delegate_to:  "{{ swarm_manager_inventory_name }}"
  changed_when: False

- name: Join Swarm
  shell:
    docker swarm join
      --token {{ swarm_token.stdout }}
  register:      swarm_result
  changed_when:  False
  ignore_errors: True
